language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

install:
  - pip install .  # See setup.py
  - pip install coveralls

script: nosetests -v -d --with-coverage --cover-package=tracer --cover-inclusive

notifications:
  email: false

after_success:
  coveralls
