language: python

python:
  - "2.7"
  - "3.3"

install:
  - pip install .
  - pip install coveralls

script: nosetests -v -d --with-coverage --cover-package=tracer --cover-inclusive

notifications:
  email: false

after_success:
  coveralls
